// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epqbvjxlmeuayjunjjwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwcWJ2anhsbWV1YXlqdW5qanduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDI3MTMsImV4cCI6MjA2NDg3ODcxM30.e-ww3kj2Oarzyd4Bx0CP_WpcTi4W5RqlMifqCdpGQUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);